Desafio.DescubraAssassino.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Desafio.DescubraAssassino.Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Desafio.DescubraAssassino.Web/Controllers/InvestigacaoController.cs
using Desafio.DescubraAssassino.Domain;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace Desafio.DescubraAssassino.Web.Controllers
{
    public class InvestigacaoController : Controller
    {
		private IDataContext dataContext;

		public InvestigacaoController()
		{
			dataContext = new DataContext(Path.Combine(HostingEnvironment.ApplicationPhysicalPath, @"App_Data\data.json"));
		}


        //
        // GET: /Investigacao/
		[HttpGet]
        public ActionResult Index()
        {
			Case caseInvestigation = this.GetCase();

            return View(caseInvestigation);
        }

		private Case GetCase()
		{
			Case caseInvestigation = new Case()
			{
				Title = "O assasinato de Bill G",
				Guns = dataContext.Guns,
				Locals = dataContext.Locals,
				Suspects = dataContext.Suspects
			};

			return caseInvestigation;
		}

		[HttpGet]
		public ActionResult Investigar()
		{
			return View("_Investigar", this.dataContext.Responses);
		}

		[HttpPost]
		public ActionResult Investigar(int response)
		{
			Detective detective = new Detective("Lin Ust Orvalds");

			Witness witness = new Witness(this.dataContext.Responses.ToList()[response]);

			Case caseInvestigation = this.GetCase();

			Response resposeOfCase = detective.SolveCase(caseInvestigation, witness);

			return View("_RespotaInvestigacao", resposeOfCase);
		}
    }
}

Desafio.DescubraAssassino.Web/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Index";
}

<div class="jumbotron">
	<h2>O assassinato de Bill G.</h2>
	<p class="lead">O empresário Bill G. Ates foi assassinado e o corpo dele foi deixado na frente da delegacia de polícia. O detetive Lin Ust Orvalds foi escolhido para investigar este caso. Após uma série de investigações, ele organizou uma lista com prováveis assassinos, os locais do crime e quais armas poderiam ter sido utilizadas.</p>

	<p class="lead">Uma testemunha foi encontrada, mas ela só consegue responder se o detetive Lin Ust Orvalds fornecer uma teoria. Para cada teoria, o detetive "chuta" um assassino, um local e uma arma. A testemunha, então, responde com um número. Se a teoria estiver correta (assassino, local e arma corretos), ela responde 0. Se a teoria está errada, um valor 1, 2 ou 3 é retornado. O valor 1 indica que o assassino(a) está incorreto; 2 indica que o local está incorreto; 3 indica que a arma está incorreta.</p>
	
	<p><a href="@Url.Action("index", "investigacao")" class="btn btn-large btn-success">Iniciar investigação</a></p>
</div>

Desafio.DescubraAssassino.Web/Views/Investigacao/Index.cshtml
@model Desafio.DescubraAssassino.Domain.Case

@{
	ViewBag.Title = "Index";
}

@section scripts{

	<script type="text/javascript">
		$(function () {
			$("#formInverstigar").submit(function () {
				var options = {
					dataType: "html",
					cache: false,
					type: "POST",
					data: $(this).serialize()
				};

				$.ajax("/investigacao/investigar", options).done(function (result) {
						$(".response").html(result);
				});

				return false;
			});
		});
	</script>
}

<br />
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<div class="thumbnail">
				<div class="caption">
					<h3>Lista de Suspeito</h3>
					<ul>
						@foreach (var item in Model.Suspects)
	  {
							<li>
								@item
							</li>
	  }
					</ul>
				</div>
			</div>
		</div>
		<div class="col-lg-4">
			<div class="thumbnail">
				<div class="caption">
					<h3>Lista de Armas</h3>
					<ul>
						@foreach (var item in Model.Guns)
	  {
							<li>
								@item
							</li>
	  }
					</ul>
				</div>
			</div>
		</div>
		<div class="col-lg-4">
			<div class="thumbnail">
				<div class="caption">
					<h3>Lista de Locais</h3>
					<ul>
						@foreach (var item in Model.Locals)
	  {
							<li>
								@item
							</li>
	  }
					</ul>
				</div>
			</div>
		</div>
	</div>

	<br />
	<div class="container">
		@{Html.RenderAction("Investigar", "Investigacao");}
	</div>

</div>

Desafio.DescubraAssassino.Web/Views/Investigacao/_Investigar.cshtml
@model IEnumerable<Desafio.DescubraAssassino.Domain.Response>

<div class="thumbnail col-lg-12">
	<div class="caption row">
		<div class="col-lg-4">
			<div class="thumbnail caption">
				<form id="formInverstigar" action="@Url.Action("investigar", "investigacao")" method="post">
					<fieldset>
						<legend>Investigar</legend>
						<div class="form-group">
							<label for="exampleInputEmail">Testemunha:</label>
							@{
								int index = 0;
								foreach (var response in Model)
								{
								<div class="radio">
									<label>
										@if (index == 0)
										{
											<input type="radio" name="response" value="@index" checked/>
										}
										else
										{
											<input type="radio" name="response" value="@index"/>			   
										}
										Resposta @(index + 1)
									</label>
								</div>
									index++;
								}
							}
						</div>
						<button type="submit" class="btn btn-primary">Inivivar</button>
					</fieldset>
				</form>
			</div>
		</div>
			<div class="col-lg-1"></div>
		<div class="response">
			
		</div>
</div>

Desafio.DescubraAssassino.Web/Views/Investigacao/_RespotaInvestigacao.cshtml
@model Desafio.DescubraAssassino.Domain.Response 

<div class="col-lg-6 thumbnail caption">
	<h3>Suspeito:</h3>
	<h4>@Model.Suspect</h4>

	<h3>Arma:</h3>
	<h4>@Model.Gun</h4>

	<h3>Local:</h3>
	<h4>@Model.Local</h4>

</div>

Desafio.DescubraAssassino.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	@Styles.Render("~/Content/bootstrap/css")
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
			<a class="navbar-brand" href="/">Descubra o Assassino</a>
	</div>


	<div class="container">
		@RenderBody()
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/Content/bootstrap/js")
	@RenderSection("scripts", required: false)
</body>
</html>